#!/usr/bin/env bash

VERSION=$(node -e "console.log(require('./package.json').version)")
NAME=$(node -e "console.log(require('./package.json').name.split('/').pop())")

echo "$VERSION"

docker build -t="$NAME:$VERSION" .


